export const tree = {
  name: '/',
  children: [
    {
      name: 'bgmjrlz',
      children: [
        {
          name: 'dhqzgdl',
          children: [
            {
              name: 'jjshzrhd',
              children: [
                {
                  name: 'jjshzrhd',
                  children: [],
                  level: 4,
                  files: [],
                  totalSize: 81645,
                },
              ],
              level: 3,
              files: [],
              totalSize: 0,
            },
            {
              name: 'jlfz',
              children: [],
              level: 3,
              files: [],
              totalSize: 0,
            },
            {
              name: 'vqvvwgt',
              children: [],
              level: 3,
              files: [],
              totalSize: 0,
            },
            {
              name: 'zcqbt',
              children: [],
              level: 3,
              files: [],
              totalSize: 0,
            },
          ],
          level: 2,
          files: [],
          totalSize: 0,
        },
        {
          name: 'djtchhmw',
          children: [],
          level: 2,
          files: [],
          totalSize: 0,
        },
        {
          name: 'tvq',
          children: [],
          level: 2,
          files: [],
          totalSize: 0,
        },
      ],
      level: 1,
      files: [],
      totalSize: 0,
    },
    { name: 'bhp', children: [], level: 1, files: [], totalSize: 0 },
    {
      name: 'cbcwz',
      children: [],
      level: 1,
      files: [],
      totalSize: 0,
    },
    {
      name: 'fvhmzqc',
      children: [],
      level: 1,
      files: [],
      totalSize: 0,
    },
    {
      name: 'hqmlnpn',
      children: [],
      level: 1,
      files: [],
      totalSize: 0,
    },
    {
      name: 'rbztmqjn',
      children: [],
      level: 1,
      files: [],
      totalSize: 0,
    },
    { name: 'vfrtt', children: [], level: 1, files: [], totalSize: 0 },
  ],
  files: [],
  level: 4,
  totalSize: 940213,
};
